# -*- coding: utf-8 -*-
"""ListaYecid.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EY_IvHWqDSpWb78nYEATyoqnSWTTxp5p
"""

def conjunto(c):
  if(len(c)== 0):
    return[[]]
  else: ultimo = conjunto(c[:-1])
  return ultimo + [listaC + [c[-1]] for listaC in ultimo]

def obt_sum(listica, valor, posicion, resultado):
  posibles = conjunto(listica)
  if posicion == len(posibles):
    #print('fin: ',posicion)
    return resultado
  #print('posibles: ', posibles)
  array = posibles[posicion]
  #print('array: ',array)
  if sum(array) == valor:
    resultado.append(array)
  posicion += 1
  return obt_sum(listica, valor, posicion, resultado) 

    
a = [1,2,3,4,5,6]
print(obt_sum(a,10, 0, []))